version: "3"

services:
  bot_owlyfer:
    labels:
      logging: true
    build:
      context: .
      dockerfile: _CI/Dockerfile
    container_name: bot_owlyfer
    networks:
      - owlyfer_lan
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    container_name: postgres
    labels:
      logging: true
    networks:
      - owlyfer_lan
    volumes:
      - owlyfer_data:/data

networks:
  owlyfer_lan:
    driver: bridge

volumes:
  owlyfer_data:
